name: Post GitHub Update

on:
  release:
    types: [published]

jobs:
  post:
    name: Post To Discord
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Click Sound Repo
        uses: actions/checkout@v4
        with:
          path: click
      - name: Run Python
        id: runit
        shell: bash
        run: |
          python3 click/.github/sendupdate.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          ROLE_ID: ${{ secrets.ROLE_ID }}
          LE_RELEASE: ${{ github.event.release.html_url }}
          TAG: ${{ github.event.release.tag_name }}
          THE_MOD_ID: "beat.click-sound"
          
